name: drone_dart
description: >
  Dart client for the Drone Ci API. This package give you ability to integrate with Drone Ci API easily.
version: 1.1.1
homepage: https://github.com/amir1430/drone-dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  lints: ^1.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
dependencies:
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dio: ^4.0.6
